### ISSUE TITLE
Unable to reach to juju ssh keys in snap

### ISSUE THREAD

**Issue by esunar** [canonical/charmed-openstack-upgrader#17]
While in snap `juju scp` does not work and gives permission denied error.

**Comment by agileshaw** [comment]
I see we are using `personal-files` interface to read juju credentials from the system. Did you manually connect this interface to the app by running something like `snap connect cou:dot-local-share-juju`? This step is needed because this interface doesn't have auto-connect permission granted and would require the user to make a manual connection.

**Comment by esunar** [comment]
The problem was if snap does not `openssh-client` as `stage-packages` it cannot find the scp binary gets permission denied.
