### ISSUE TITLE
The os_release_units is not working for suboridnate charms

### ISSUE THREAD

**Issue by rgildein** [canonical/charmed-openstack-upgrader#286]
For charms without units, we will get `ValueError`, when we try to access the `os_release_units` property.

```python
    @property
    def current_os_release(self) -> OpenStackRelease:
        """Current OpenStack Release of the application.
    
        :return: OpenStackRelease object
        :rtype: OpenStackRelease
        """
>       return min(self.os_release_units.keys())
E       ValueError: min() arg is an empty sequence
```

**Comment by gabrielcocenza** [comment]
I'm not sure if this is a valid bug.

Subordinate apps will return empty dictionary on `os_release_units`, which is technically correct and  are overwriting `current_os_release` on: https://github.com/canonical/charmed-openstack-upgrader/blob/9e3a89a70c4f11518da459191a58488be42ebbfb/cou/apps/subordinate.py#L76-L94

The problem that you are facing on #280 is because you are creating a principal app (ceph-osd) without units. I'm not sure if that is even possible to deploy a principal charm without units. Adding at least one unit to ceph-osd will probably solve the unit test

**Comment by rgildein** [comment]
Yes, it will solve it, I used #280 just as [example](https://github.com/canonical/charmed-openstack-upgrader/actions/runs/8230270606/job/22503159478) with output from running without it. You can have any app with 0 units, maybe we can have filtered to skip all apps without units or something like that.

**Comment by aieri** [comment]
This could happen if a principal application has had all its units removed (but not the application). When that happens we should skip the app instead of crashing.

**Comment by Pjack** [comment]
Close this JIRA ticket. 
Refactoring has become a low priority, as Caracal will be the final release of charmed-openstack.
